name: .NET Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for solution
      run: dotnet restore TestServer/TestServer.sln

    - name: Build TestServer
      run: dotnet build --no-restore TestServer/TestServer.csproj

    - name: Build TestServerTests
      run: dotnet build --no-restore TestServerTests/TestServerTests.csproj

    - name: Run tests
      run: dotnet test --no-build --verbosity normal TestServerTests/TestServerTests.csproj

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: TestServer-build
        path: TestServer/bin/Debug/net8.0/
